name: Daily TVBox Source Update

on:
  schedule:
    - cron: '0 22 * * *'  # 每天UTC时间22点运行 (北京时间次日6点)
  workflow_dispatch:       # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run update scripts
      run: |
        python scripts/step1_official_sources.py
        python scripts/step2_tvbox_coder.py
        python scripts/step3_hebei_search.py
        python scripts/step4_merge.py

    - name: Commit changes
      run: |
        # 设置Git身份
        git config --local user.email "zyylian@qq.com"
        git config --local user.name "Lightconer"
        
        # 确保使用最新远程分支
        echo "重置工作区到远程main分支..."
        git fetch origin main
        git reset --hard origin/main
        
        # 添加并提交更改
        git add output/tvbox.m3u
        
        # 检查是否有变更
        if git diff-index --quiet HEAD --; then
          echo "没有需要提交的更改"
        else
          echo "提交更改..."
          git commit -m "Auto: Daily TVBox Source Update [$(date +'%Y-%m-%d %H:%M')]"
          
          # 强制推送更新
          echo "强制推送更改..."
          git push origin HEAD:main --force
          echo "更新推送完成"
        fi
